language: java
jdk:
 - oraclejdk8

notifications:
  email:
    - dqonline@ducquoc.net

install: true
script: 
 - mvn clean install -Dmaven.javadoc.skip=true -Ddockerfile.skip -B -V -f cc-dq/execute-cc/pom.xml
